/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;





import bourseapp.infos;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.DefaultComboBoxModel;
import java.sql.Connection;
 
import java.sql.DriverManager;
import java.text.ParseException;
import java.util.Scanner;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Abdelatif Hamdi
 */
public class frmInfos extends javax.swing.JFrame {

    /**
     * Creates new form infos
     */
    public frmInfos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TextNomFr = new controls.JTextBox(13);
        TextNomAr = new controls.JTextBox(13);
        TextNum = new controls.JTextBox(13);
        ComBénéf = new controls.JMyCombo();
        TextDateN = new com.toedter.calendar.JDateChooser();
        ComSexe = new controls.JMyCombo();
        ComGrade = new controls.JMyCombo();
        TextDurée = new controls.JTextBox(5);
        TextDateD = new com.toedter.calendar.JDateChooser();
        TextDateF = new com.toedter.calendar.JDateChooser();
        ComPays = new controls.JMyCombo();
        TextEtab = new controls.JTextBox(13);
        ComDomaine = new controls.JMyCombo();
        ComTypeStage = new controls.JMyCombo();
        TextAllocation = new controls.JTextBox(13);
        TextBillet = new controls.JTextBox(13);
        ComFaculté = new controls.JMyCombo();
        btnModifier = new controls.JMyBottom();
        btnAjouter = new controls.JMyBottom();
        btnEffacer = new controls.JMyBottom();
        btnTrouver = new controls.JMyBottom();
        btnTout = new controls.JMyBottom();
        BtnImprimer = new controls.JMyBottom();
        btnSup = new controls.JMyBottom();
        jLabel19 = new javax.swing.JLabel();
        TextAnnFinac = new com.toedter.calendar.JYearChooser();
        btnCalcul = new controls.JMyBottom();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabInfos = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        btnRecherche = new controls.JMyBottom();
        TextRecherche = new controls.JTextBox(30);
        rechCom = new controls.JMyCombo();
        btnEffacer1 = new controls.JMyBottom();
        jButton1 = new controls.JMyBottom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Le numéro :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Bénéficiaire :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nom et prénom en Arabe : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nom et prénom en Français :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Date de naissance :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Sexe :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Grade :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Durée :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Date de départ :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Date d’arrivé :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Pays d’accueil :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Etablissement d’accueil :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Domaine :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Type de stage :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Allocation :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Billet:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Année Financière :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Faculté :");

        TextNomAr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomArActionPerformed(evt);
            }
        });

        TextNum.setEditable(false);

        ComBénéf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComBénéfItemStateChanged(evt);
            }
        });
        ComBénéf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComBénéfActionPerformed(evt);
            }
        });

        TextDurée.setEditable(false);

        TextAllocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextAllocationActionPerformed(evt);
            }
        });

        TextBillet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextBilletActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        btnTrouver.setText("Trouver");
        btnTrouver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrouverActionPerformed(evt);
            }
        });

        btnTout.setText("Tout");
        btnTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToutActionPerformed(evt);
            }
        });

        BtnImprimer.setText("Imprimer");
        BtnImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimerActionPerformed(evt);
            }
        });

        btnSup.setText("Supprimer");
        btnSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel19.setText("Informations de Bénéficiaire");

        btnCalcul.setText("Calculer");
        btnCalcul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setToolTipText("");

        TabInfos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numéro", "Bénéficiaire", "Nom&PreAr", "Nom&PreFr", "Date naissance", "Sexe", "Grade", "Durée", "Date départ", "Date arrivé", "PaysAcc", "EtabAcc", "Domaine", "Type stage", "Allocation", "Billet", "Année financière", "Faculté"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabInfos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TabInfos.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        TabInfos.setRowHeight(20);
        TabInfos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabInfosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabInfos);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Rechercher avec :");

        btnRecherche.setText("Recherche");
        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });

        TextRecherche.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        btnEffacer1.setText("Rapport");
        btnEffacer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacer1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/excel.png"))); // NOI18N
        jButton1.setText(" Importer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNomAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComBénéf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextEtab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNomFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextAnnFinac, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComGrade, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(ComSexe, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(TextDateN, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(TextDateD, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(TextDateF, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(ComPays, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(ComDomaine, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(ComTypeStage, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TextDurée, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(btnCalcul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextAllocation)
                            .addComponent(TextBillet)
                            .addComponent(ComFaculté, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 39, Short.MAX_VALUE)
                        .addComponent(BtnImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTrouver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEffacer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rechCom, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addGap(191, 191, 191)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnImprimer, btnAjouter, btnEffacer, btnEffacer1, btnModifier, btnSup, btnTout, btnTrouver});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ComBénéf, ComDomaine, ComFaculté, ComGrade, ComPays, ComSexe, ComTypeStage, TextAllocation, TextBillet, TextDateD, TextDateF, TextDateN, TextEtab, TextNomAr, TextNomFr, TextNum});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TextNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(TextRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rechCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ComBénéf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextNomAr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TextNomFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(TextDateN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(ComSexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(ComGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextDurée, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCalcul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(TextDateD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(TextDateF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(ComPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(TextEtab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(ComDomaine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(ComTypeStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(TextAllocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(TextBillet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(TextAnnFinac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(ComFaculté, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTrouver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEffacer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnImprimer, btnAjouter, btnEffacer, btnEffacer1, btnModifier, btnSup, btnTout, btnTrouver});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNomArActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomArActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomArActionPerformed
infos i = new infos();
private void setValues(){
    i.setNuméro(Integer.parseInt(TextNum.getText()));
    i.setBénéficiaire(ComBénéf.getSelectedItem().toString());
    i.setNomPreAr(TextNomAr.getText());
    i.setNomPreFr(TextNomFr.getText());
    SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
    i.setDateNaissance(String.valueOf(s.format(TextDateN.getDate())));
    i.setSexe(ComSexe.getSelectedItem().toString());
    i.setGrade(ComGrade.getSelectedItem().toString());
    i.setDurée(TextDurée.getText());
    i.setDateDepart(String.valueOf(s.format(TextDateD.getDate())));
    i.setDateArrivé(String.valueOf(s.format(TextDateF.getDate())));
    i.setPaysAcc(ComPays.getSelectedItem().toString());
    i.setEtabAcc(TextEtab.getText());
    i.setDomaine(ComDomaine.getSelectedItem().toString());
    i.setTypeStage(ComTypeStage.getSelectedItem().toString());
    i.setAllocation(Double.parseDouble(TextAllocation.getText()));
    i.setBillet(Double.parseDouble(TextBillet.getText()));
    i.setAnnéeFinac((int) TextAnnFinac.getValue());
    i.setFaculté(ComFaculté.getSelectedItem().toString());
}
private void Clear(){
    Tools.Tools.ClearTexts(this);
    TextNum.setText(db.go.getAutoNumber("infos", "numB"));
            DefaultTableModel model = (DefaultTableModel) TabInfos.getModel();
        model.setNumRows(0);
    btnAjouter.setEnabled(true);
    btnModifier.setEnabled(false);
    btnSup.setEnabled(false);
    //ComBénéf.requestFocus();
}
    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        setValues();
        i.update();
        Clear();
        i.getAllRows(TabInfos);
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        setValues();
        i.add();
        Clear();
        i.getAllRows(TabInfos);
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnEffacerActionPerformed

    private void btnTrouverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrouverActionPerformed
        String strNum = (String) Tools.Tools.InputBox("Entrer le Numéro de Bénéficiaire ...");
        int Num = Integer.parseInt(strNum);
        i.setNuméro(Num);
        i.getOneRow(TabInfos);

    }//GEN-LAST:event_btnTrouverActionPerformed

    private void btnToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToutActionPerformed
        // TODO add your handling code here:
        i.getAllRows(TabInfos);
    }//GEN-LAST:event_btnToutActionPerformed

    private void BtnImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimerActionPerformed
 Tools.Tools.OpenForm((new frmTable()));
    }//GEN-LAST:event_BtnImprimerActionPerformed

    private void btnSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupActionPerformed
        if(Tools.Tools.ConfirmMessage("Voulez vous supprimer ? ")){
        setValues();
        i.delete();
        Clear();
        i.getAllRows(TabInfos);}
    }//GEN-LAST:event_btnSupActionPerformed

    private void TextBilletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextBilletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextBilletActionPerformed
 String gradeProf[]=new String[8];
 String gradeEmp[]=new String[3];
 String gradeDoc[]=new String[2];

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

Clear();
        i.getAllRows(TabInfos);
        String rechTab[] = new String[17];
        rechTab[0]="Bénéficiaire";rechTab[1]="Nom et prénom en Arabe";rechTab[2]="Nom et prénom en Français";rechTab[3]="Date de naissance";rechTab[4]="Sexe";rechTab[5]="Grade";
        rechTab[6]="Durée";rechTab[7]="Date de départ";rechTab[8]="Date d’arrivé";rechTab[9]="Pays d’accueil";rechTab[10]="Etablissement d’accueil";rechTab[11]="Domaine";
        rechTab[12]="Type de stage";rechTab[13]="Allocation";rechTab[14]="Billet";rechTab[15]="Année Financière";rechTab[16]="Faculté";
        rechCom.setModel(new DefaultComboBoxModel(rechTab));
        String benTab[] = new String[3];
        benTab[0]="Maître";benTab[1]="Employé";benTab[2]="Doctorant";
        ComBénéf.setModel(new DefaultComboBoxModel(benTab));
        String sexeTab[] = new String[2];
        sexeTab[0]="M"; sexeTab[1]="F";
        ComSexe.setModel(new DefaultComboBoxModel(sexeTab));
        gradeProf[0]="PROF";gradeProf[1]="MCA";gradeProf[2]="MCB";gradeProf[3]="MAA";
        gradeProf[4]="MAB";gradeProf[5]="MC HU A";gradeProf[6]="MC HU B";gradeProf[7]="MA HU";
        gradeEmp[0]="APPLICATION";gradeEmp[1]="MAITRISE";gradeEmp[2]="EXECECUTION";
        gradeDoc[0]="ETUD DLMD"; gradeDoc[1]="ETUD  MASTER";
        ComGrade.setModel(new DefaultComboBoxModel(gradeProf));
        String PaysAcc[]= new String[35];
        PaysAcc[0]="Afrique du Sud";PaysAcc[1]="Allemagne";PaysAcc[2]="Arabie Saoudite";PaysAcc[3]="Bahreïn";PaysAcc[4]="Belgique";PaysAcc[5]="Brésil";PaysAcc[6]="Canada";PaysAcc[7]="Chili";
        PaysAcc[8]="Chine";PaysAcc[9]="Egypte";PaysAcc[10]="Emirate Arabs Unis";PaysAcc[11]="Espagne";PaysAcc[12]="Etats-Unis d'Amérique";PaysAcc[13]="Finlande";PaysAcc[14]="France";PaysAcc[15]="Hollande";
        PaysAcc[16]="Hongrie";PaysAcc[17]="Ile Maurice";PaysAcc[18]="Italie";PaysAcc[19]="Jordanie";PaysAcc[20]="Koweït";PaysAcc[21]="Liban";PaysAcc[22]="Malaisie";PaysAcc[23]="Malaysia";
        PaysAcc[24]="Maroc";PaysAcc[25]="Oman";PaysAcc[26]="Portugal";PaysAcc[27]="Qatar";PaysAcc[28]="Royaume-Uni";PaysAcc[29]="Russie";PaysAcc[30]="Stockholm";PaysAcc[31]="Suisse";
        PaysAcc[32]="Tchèque";PaysAcc[33]="Tunisie";PaysAcc[34]="Turquie";
        ComPays.setModel(new DefaultComboBoxModel(PaysAcc));
        String dom[]= new String[12];
        dom[0]="S.T";dom[1]="A.U.M.V";dom[2]="M.I";dom[3]="S.M";dom[4]="S.N.V";dom[5]="S.E.C.G";dom[6]="D.S.P";dom[7]="L.L.A";dom[8]="L.L.E";dom[9]="S.S.H";dom[10]="STAPS";dom[11]="SC.MEDICALES";
        ComDomaine.setModel(new DefaultComboBoxModel(dom));
        String[] typeS = new String[3]; typeS[0]="Stage de courte durée";typeS[1]="Stage de longe durée";typeS[2]="Séjour scientifique de haut niveau";
        ComTypeStage.setModel(new DefaultComboBoxModel(typeS));
        String fac[] = new String[10]; fac[0]="DROIT ET SCIENCES POLIYIQUES";fac[1]="GENIE CIVIL ET D'AECHITECTURE";
        fac[2]="INSTITUT STAPS";fac[3]="LETTRES ET DES LANGUES";fac[4]="MEDECINE";fac[5]="SCIENCE";
        fac[6]="SCIENCE ECONOMIQUE,COMMERCIALES ET SCIENCES DE GESTIONS";fac[7]="SCIENCE HUMAINES,ISLAMIQUES ET CIVILISATION";
        fac[8]="SCIENCE SOCIALES";fac[9]="TECHNOLOGIE";
        ComFaculté.setModel(new DefaultComboBoxModel(fac));
        TabInfos.getTableHeader().setReorderingAllowed(false);
        TabInfos.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
TabInfos.getTableHeader().setOpaque(false);
TabInfos.getTableHeader().setBackground(new Color(32, 136, 203)); TextNomAr.requestFocus();
TabInfos.getTableHeader().setForeground(new Color(255, 255, 255));    }//GEN-LAST:event_formWindowOpened

    private void TabInfosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabInfosMouseClicked
try{int row = TabInfos.getSelectedRow();
TextNum.setText(TabInfos.getValueAt(row, 0).toString());
ComBénéf.setSelectedItem(TabInfos.getValueAt(row, 1).toString());
TextNomAr.setText(TabInfos.getValueAt(row, 2).toString());
TextNomFr.setText(TabInfos.getValueAt(row, 3).toString());
SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
TextDateN.setDate(s.parse(TabInfos.getValueAt(row, 4).toString()));
ComSexe.setSelectedItem(TabInfos.getValueAt(row, 5).toString());
ComGrade.setSelectedItem(TabInfos.getValueAt(row, 6).toString());
TextDurée.setText(TabInfos.getValueAt(row, 7).toString());
TextDateD.setDate(s.parse(TabInfos.getValueAt(row, 8).toString()));
TextDateF.setDate(s.parse(TabInfos.getValueAt(row, 9).toString()));
ComPays.setSelectedItem(TabInfos.getValueAt(row, 10).toString());
TextEtab.setText(TabInfos.getValueAt(row, 11).toString());
ComDomaine.setSelectedItem(TabInfos.getValueAt(row, 12).toString());
ComTypeStage.setSelectedItem(TabInfos.getValueAt(row, 13).toString());
TextAllocation.setText(TabInfos.getValueAt(row, 14).toString());
TextBillet.setText(TabInfos.getValueAt(row, 15).toString());
TextAnnFinac.setValue(Integer.parseInt(TabInfos.getValueAt(row, 16).toString()));
ComFaculté.setSelectedItem(TabInfos.getValueAt(row, 17).toString());
btnAjouter.setEnabled(false);
         btnModifier.setEnabled(true);
         btnSup.setEnabled(true);
} catch (Exception ex){
Tools.Tools.Message(ex);
}
    }//GEN-LAST:event_TabInfosMouseClicked

    private void ComBénéfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComBénéfItemStateChanged
if (    null == this.ComBénéf.getSelectedItem().toString())
    this.ComGrade.setModel(new DefaultComboBoxModel(gradeDoc));
else    switch (this.ComBénéf.getSelectedItem().toString()) {
            case "Maître":
                this.ComGrade.setModel(new DefaultComboBoxModel(gradeProf));
                break;
            case "Employé":
                this.ComGrade.setModel(new DefaultComboBoxModel(gradeEmp));
                break;
            default:
                this.ComGrade.setModel(new DefaultComboBoxModel(gradeDoc));
                break;
        }
    }//GEN-LAST:event_ComBénéfItemStateChanged

    private void ComBénéfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComBénéfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComBénéfActionPerformed

    private void TextAllocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAllocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAllocationActionPerformed

    private void btnCalculActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculActionPerformed
if ((this.TextDateD.getDate()!=null)&&(this.TextDateF.getDate()!=null))
{
DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy"); // format jour / mois / année
Date date1 = this.TextDateF.getDate();
Date date2 = this.TextDateD.getDate();
//Period period = Period.between(date1,date2 );
//String d = ChronoUnit.DAYS.between((Temporal) date1, (Temporal) date2) + "";
long diffInMillies = Math.abs(date1.getTime() - date2.getTime());
    long diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
this.TextDurée.setText(diff+"");

}
    }//GEN-LAST:event_btnCalculActionPerformed

    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        // TODO add your handling code here:
        String cherche ="select * from infos where ";
        switch (rechCom.getSelectedIndex()) {
            case 0:
                cherche+="benf='"+TextRecherche.getText()+"'";
                break;
            case 1:
                cherche+="nomPreAr like'%"+TextRecherche.getText()+"%'";
                break;
            case 2:
                cherche+="nomPreFr like'%"+TextRecherche.getText()+"%'";
                break;
            case 3:
                cherche+="dateN='"+TextRecherche.getText()+"'";
                break;
            case 4:
                cherche+="sexe='"+TextRecherche.getText()+"'";
                break;
            case 5:
                cherche+="grade='"+TextRecherche.getText()+"'";
                break;
            case 6:
                cherche+="durée="+TextRecherche.getText();
                break;
            case 7:
                cherche+="dateD='"+TextRecherche.getText()+"'";
                break;
            case 8:
                cherche+="dateF='"+TextRecherche.getText()+"'";
                break;
            case 9:
                cherche+="paysAcc='"+TextRecherche.getText()+"'";
                break;
            case 10:
                cherche+="etabAcc='"+TextRecherche.getText()+"'";
                break;
            case 11:
                cherche+="domaine='"+TextRecherche.getText()+"'";
                break;
            case 12:
                cherche+="typeStage='"+TextRecherche.getText()+"'";
                break;
            case 13:
                cherche+="allocation="+TextRecherche.getText();
                break;
            case 14:
                cherche+="billet="+TextRecherche.getText();
                break;
            case 15:
                cherche+="annFinac="+TextRecherche.getText();
                break;
            case 16:
                cherche+="faculté='"+TextRecherche.getText()+"'";
                break;
            default:
                break;
        }

        i.getCustomRows(cherche, TabInfos);
        

    }//GEN-LAST:event_btnRechercheActionPerformed

    private void btnEffacer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacer1ActionPerformed

       try{
 
      Class.forName("com.mysql.jdbc.Driver");
       Connection con =     DriverManager.getConnection("jdbc:mysql://localhost:3306/bourse?useUnicode=true&characterEncoding=UTF-8","root","");
       String reportPath = "infos.jrxml";
           /*JasperDesign jd = JRXmlLoader.load(reportPath);
           String sql = "select ...";*/
       JasperReport jr = JasperCompileManager.compileReport(reportPath);
       JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
       JasperViewer.viewReport(jp,false);
       con.close();
}
 
catch(Exception ex)
{
    Tools.Tools.Message(ex);
}
    }//GEN-LAST:event_btnEffacer1ActionPerformed
private String[] getCells(String enrg){
String cells[]=new String[18];
int j=0;
for(int k=0;k<18;k++){
cells[k]="";
while(j<enrg.length()){
if (enrg.charAt(j)==','){
j++; break;
} else{
cells[k]+=enrg.charAt(j); j++;
}}}
return cells;}


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    JFileChooser jfc = new JFileChooser();
int test = jfc.showOpenDialog(null);
if(test == JFileChooser.APPROVE_OPTION)
{
File exf = jfc.getSelectedFile();
            SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat sf2 = new SimpleDateFormat("dd/MM/yyyy");
if (".csv".equals(Tools.Tools.getFileExtension(exf))){
try {
        Scanner inputStream = new Scanner(exf);
        while (inputStream.hasNext()){
            String data = inputStream.nextLine();
            String cells[] = getCells(data);
            String insert ="insert into infos values("
                +cells[0]+",'"+cells[1]+"','"+cells[2]+"','"+cells[3]+"','"
        +String.valueOf(sf.format(sf2.parse(cells[4])))+"','"+cells[5]+"','"+cells[6]+"','"+cells[7]+
        "','"+String.valueOf(sf.format(sf2.parse(cells[8])))+"','"+String.valueOf(sf.format(sf2.parse(cells[9])))+"','"+cells[10]+"','"+cells[11]+
        "','"+cells[12]+"','"+cells[13]+"',"+cells[14]
        +","+cells[15]+","+cells[16]+",'"+cells[17]+"')";
        db.go.RunNonQuery(insert);
        }
        inputStream.close();

    } catch (FileNotFoundException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }
    
}else if (".xls".equals(Tools.Tools.getFileExtension(exf))){
    Workbook wb = Workbook.getWorkbook(exf);
    Sheet s = wb.getSheet(0);
    int Rows = s.getRows(); 
for (int n = 0 ;n<Rows;n++){
String insert ="insert into infos values("
                +s.getCell(0, n).getContents()+",'"+s.getCell(1, n).getContents()+"','"+s.getCell(2, n).getContents()+"','"+s.getCell(3, n).getContents()+"','"
        +String.valueOf(sf.format(sf2.parse(s.getCell(4, n).getContents())))+"','"+s.getCell(5, n).getContents()+"','"+s.getCell(6, n).getContents()+"','"+s.getCell(7, n).getContents()+
        "','"+String.valueOf(sf.format(sf2.parse(s.getCell(8, n).getContents())))+"','"+String.valueOf(sf.format(sf2.parse(s.getCell(9, n).getContents())))+"','"+s.getCell(10, n).getContents()+"','"+s.getCell(11, n).getContents()+
        "','"+s.getCell(12, n).getContents()+"','"+s.getCell(13, n).getContents()+"',"+s.getCell(14, n).getContents()
        +","+s.getCell(15, n).getContents()+","+s.getCell(16, n).getContents()+",'"+s.getCell(17, n).getContents()+"')";
        db.go.RunNonQuery(insert);
}}
Tools.Tools.Message("Le fichier excle est importé avec succès");
i.getAllRows(TabInfos);
}} catch (HeadlessException | IOException | IndexOutOfBoundsException | ParseException | BiffException ex){
            Tools.Tools.Message(ex);
}


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInfos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInfos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyBottom BtnImprimer;
    private controls.JMyCombo ComBénéf;
    private controls.JMyCombo ComDomaine;
    private controls.JMyCombo ComFaculté;
    private controls.JMyCombo ComGrade;
    private controls.JMyCombo ComPays;
    private controls.JMyCombo ComSexe;
    private controls.JMyCombo ComTypeStage;
    public static javax.swing.JTable TabInfos;
    private javax.swing.JTextField TextAllocation;
    private com.toedter.calendar.JYearChooser TextAnnFinac;
    private javax.swing.JTextField TextBillet;
    private com.toedter.calendar.JDateChooser TextDateD;
    private com.toedter.calendar.JDateChooser TextDateF;
    private com.toedter.calendar.JDateChooser TextDateN;
    private javax.swing.JTextField TextDurée;
    private javax.swing.JTextField TextEtab;
    private javax.swing.JTextField TextNomAr;
    private javax.swing.JTextField TextNomFr;
    private javax.swing.JTextField TextNum;
    private javax.swing.JTextField TextRecherche;
    private controls.JMyBottom btnAjouter;
    private controls.JMyBottom btnCalcul;
    private controls.JMyBottom btnEffacer;
    private controls.JMyBottom btnEffacer1;
    private javax.swing.ButtonGroup btnGroup;
    private controls.JMyBottom btnModifier;
    private controls.JMyBottom btnRecherche;
    private controls.JMyBottom btnSup;
    private controls.JMyBottom btnTout;
    private controls.JMyBottom btnTrouver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private controls.JMyCombo rechCom;
    // End of variables declaration//GEN-END:variables
}
