/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import static Tools.Tools.Message;
import java.awt.Color;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Abdelatif Hamdi
 */
public class frmTable extends javax.swing.JFrame {

    /**
     * Creates new form frmTable
     */
    public frmTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabInfosMini = new javax.swing.JTable();
        checkNuméro = new javax.swing.JCheckBox();
        checkDateD = new javax.swing.JCheckBox();
        checkDurée = new javax.swing.JCheckBox();
        checkGrade = new javax.swing.JCheckBox();
        checkNomAr = new javax.swing.JCheckBox();
        checkBénéficiaire = new javax.swing.JCheckBox();
        checkSexe = new javax.swing.JCheckBox();
        checkDateN = new javax.swing.JCheckBox();
        checkNomFr = new javax.swing.JCheckBox();
        checkBillet = new javax.swing.JCheckBox();
        checkEtabAcc = new javax.swing.JCheckBox();
        checkPaysAcc = new javax.swing.JCheckBox();
        checkAllocation = new javax.swing.JCheckBox();
        checkTypeS = new javax.swing.JCheckBox();
        checkDomaine = new javax.swing.JCheckBox();
        checkDateF = new javax.swing.JCheckBox();
        checkFac = new javax.swing.JCheckBox();
        checkAnn = new javax.swing.JCheckBox();
        BtnImprimerMini = new controls.JMyBottom();
        jMyBottom1 = new controls.JMyBottom();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        TabInfosMini.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numéro", "Bénéficiaire", "Nom&PreAr", "Nom&PreFr", "Date naissance", "Sexe", "Grade", "Durée", "Date départ", "Date arrivé", "PaysAcc", "EtabAcc", "Domaine", "Type stage", "Allocation", "Billet", "Année financière", "Faculté"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabInfosMini.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TabInfosMini.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        TabInfosMini.setRowHeight(20);
        TabInfosMini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabInfosMiniMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabInfosMini);

        checkNuméro.setBackground(new java.awt.Color(255, 255, 255));
        checkNuméro.setSelected(true);
        checkNuméro.setText("Numéro");
        checkNuméro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNuméroActionPerformed(evt);
            }
        });

        checkDateD.setBackground(new java.awt.Color(255, 255, 255));
        checkDateD.setSelected(true);
        checkDateD.setText("Date départ");

        checkDurée.setBackground(new java.awt.Color(255, 255, 255));
        checkDurée.setSelected(true);
        checkDurée.setText("Durée");

        checkGrade.setBackground(new java.awt.Color(255, 255, 255));
        checkGrade.setSelected(true);
        checkGrade.setText("Grade");

        checkNomAr.setBackground(new java.awt.Color(255, 255, 255));
        checkNomAr.setSelected(true);
        checkNomAr.setText("Nom&PreAr");

        checkBénéficiaire.setBackground(new java.awt.Color(255, 255, 255));
        checkBénéficiaire.setSelected(true);
        checkBénéficiaire.setText("Bénéficiaire");

        checkSexe.setBackground(new java.awt.Color(255, 255, 255));
        checkSexe.setSelected(true);
        checkSexe.setText("Sexe");

        checkDateN.setBackground(new java.awt.Color(255, 255, 255));
        checkDateN.setSelected(true);
        checkDateN.setText("Date naissance");

        checkNomFr.setBackground(new java.awt.Color(255, 255, 255));
        checkNomFr.setSelected(true);
        checkNomFr.setText("Nom&PreFr");
        checkNomFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNomFrActionPerformed(evt);
            }
        });

        checkBillet.setBackground(new java.awt.Color(255, 255, 255));
        checkBillet.setSelected(true);
        checkBillet.setText("Billet");

        checkEtabAcc.setBackground(new java.awt.Color(255, 255, 255));
        checkEtabAcc.setSelected(true);
        checkEtabAcc.setText("EtabAcc");

        checkPaysAcc.setBackground(new java.awt.Color(255, 255, 255));
        checkPaysAcc.setSelected(true);
        checkPaysAcc.setText("PaysAcc");

        checkAllocation.setBackground(new java.awt.Color(255, 255, 255));
        checkAllocation.setSelected(true);
        checkAllocation.setText("Allocation");

        checkTypeS.setBackground(new java.awt.Color(255, 255, 255));
        checkTypeS.setSelected(true);
        checkTypeS.setText("Type stage");
        checkTypeS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTypeSActionPerformed(evt);
            }
        });

        checkDomaine.setBackground(new java.awt.Color(255, 255, 255));
        checkDomaine.setSelected(true);
        checkDomaine.setText("Domaine");
        checkDomaine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDomaineActionPerformed(evt);
            }
        });

        checkDateF.setBackground(new java.awt.Color(255, 255, 255));
        checkDateF.setSelected(true);
        checkDateF.setText("Date arrivé");
        checkDateF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDateFActionPerformed(evt);
            }
        });

        checkFac.setBackground(new java.awt.Color(255, 255, 255));
        checkFac.setSelected(true);
        checkFac.setText("Faculté");

        checkAnn.setBackground(new java.awt.Color(255, 255, 255));
        checkAnn.setSelected(true);
        checkAnn.setText("Année Financière");

        BtnImprimerMini.setText("Imprimer");
        BtnImprimerMini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimerMiniActionPerformed(evt);
            }
        });

        jMyBottom1.setText("Afficher");
        jMyBottom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMyBottom1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("sélectionner les colonnes :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkNuméro)
                        .addGap(2, 2, 2)
                        .addComponent(checkBénéficiaire))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkDateF)
                        .addGap(2, 2, 2)
                        .addComponent(checkPaysAcc)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkNomAr)
                        .addGap(2, 2, 2)
                        .addComponent(checkNomFr)
                        .addGap(0, 0, 0)
                        .addComponent(checkDateN)
                        .addGap(0, 0, 0)
                        .addComponent(checkSexe)
                        .addGap(0, 0, 0)
                        .addComponent(checkGrade)
                        .addGap(2, 2, 2)
                        .addComponent(checkDurée)
                        .addGap(2, 2, 2)
                        .addComponent(checkDateD))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(checkEtabAcc)
                        .addGap(2, 2, 2)
                        .addComponent(checkDomaine)
                        .addGap(0, 0, 0)
                        .addComponent(checkTypeS)
                        .addGap(0, 0, 0)
                        .addComponent(checkAllocation)
                        .addGap(0, 0, 0)
                        .addComponent(checkBillet)
                        .addGap(2, 2, 2)
                        .addComponent(checkAnn)
                        .addGap(2, 2, 2)
                        .addComponent(checkFac)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(BtnImprimerMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jMyBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnImprimerMini, jMyBottom1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkNuméro)
                            .addComponent(checkBénéficiaire))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkDateF)
                            .addComponent(checkPaysAcc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkNomAr)
                            .addComponent(checkNomFr)
                            .addComponent(checkDateN)
                            .addComponent(checkSexe)
                            .addComponent(checkGrade)
                            .addComponent(checkDurée)
                            .addComponent(checkDateD))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkEtabAcc)
                            .addComponent(checkDomaine)
                            .addComponent(checkTypeS)
                            .addComponent(checkAllocation)
                            .addComponent(checkBillet)
                            .addComponent(checkAnn)
                            .addComponent(checkFac))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnImprimerMini, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMyBottom1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnImprimerMini, jMyBottom1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabInfosMiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabInfosMiniMouseClicked
        
    }//GEN-LAST:event_TabInfosMiniMouseClicked

    private void checkNomFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNomFrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkNomFrActionPerformed

    private void checkDomaineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDomaineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDomaineActionPerformed

    private void BtnImprimerMiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimerMiniActionPerformed
        // TODO add your handling code here:
        try {
            MessageFormat header = new MessageFormat("Rapport des bénéficiares");
            MessageFormat footer = new MessageFormat("Page - {0}");
            TabInfosMini.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Message(ex.getMessage());
        }
        /* try{
 
      Class.forName("com.mysql.jdbc.Driver");
       Connection con =     DriverManager.getConnection("jdbc:mysql://localhost/"+"bourse"+"?useUnicode=true&characterEncoding=UTF-8","root","");
       String reportPath = "Invoice_Table_Based.jrxml";
           JasperDesign jd = JRXmlLoader.load(reportPath);
           JRDesignQuery newQuery = new JRDesignQuery();
           newQuery.setText(sql);
           jd.setQuery(newQuery);
       JasperReport jr = JasperCompileManager.compileReport(jd);
       JasperPrint jp = JasperFillManager.fillReport(jr,null, con);
       JasperViewer.viewReport(jp);
       con.close();
 } catch (ClassNotFoundException | SQLException | JRException ex){
     Message(ex);

        }*/
    }//GEN-LAST:event_BtnImprimerMiniActionPerformed

    private void checkNuméroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNuméroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkNuméroActionPerformed

    private void checkTypeSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTypeSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkTypeSActionPerformed
String sql = "select ";
    private void jMyBottom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMyBottom1ActionPerformed
        
        TableColumnModel cm2 = new DefaultTableColumnModel();
        TableColumn c0 = frmInfos.TabInfos.getColumn("Numéro");
        TableColumn c1 = frmInfos.TabInfos.getColumn("Bénéficiaire");
        TableColumn c2 = frmInfos.TabInfos.getColumn("Nom&PreAr");
        TableColumn c3 = frmInfos.TabInfos.getColumn("Nom&PreFr");
        TableColumn c4 = frmInfos.TabInfos.getColumn("Date naissance");
        TableColumn c5 = frmInfos.TabInfos.getColumn("Sexe");
        TableColumn c6 = frmInfos.TabInfos.getColumn("Grade");
        TableColumn c7 = frmInfos.TabInfos.getColumn("Durée");
        TableColumn c8 = frmInfos.TabInfos.getColumn("Date départ");
        TableColumn c9 = frmInfos.TabInfos.getColumn("Date arrivé");
        TableColumn c10 = frmInfos.TabInfos.getColumn("PaysAcc");
        TableColumn c11 = frmInfos.TabInfos.getColumn("EtabAcc");
        TableColumn c12 = frmInfos.TabInfos.getColumn("Domaine");
        TableColumn c13 = frmInfos.TabInfos.getColumn("Type stage");
        TableColumn c14 = frmInfos.TabInfos.getColumn("Allocation");
        TableColumn c15 = frmInfos.TabInfos.getColumn("Billet");
        TableColumn c16 = frmInfos.TabInfos.getColumn("Année financière");
        TableColumn c17 = frmInfos.TabInfos.getColumn("Faculté");
        if (checkNuméro.isSelected()) {cm2.addColumn(c0); sql+="numB ,";}
        if (checkBénéficiaire.isSelected()) {cm2.addColumn(c1); sql+="benf ,";}
        if (checkNomAr.isSelected()) {cm2.addColumn(c2); sql+="nomPreAr ,";}
        if (checkNomFr.isSelected()) {cm2.addColumn(c3); sql+="nomPreFr ,";}
        if (checkDateN.isSelected()) {cm2.addColumn(c4); sql+="DateN ,";}
        if (checkSexe.isSelected()) {cm2.addColumn(c5); sql+="sexe ,";}
        if (checkGrade.isSelected()) {cm2.addColumn(c6); sql+="grade ,";}
        if (checkDurée.isSelected()) {cm2.addColumn(c7); sql+="durée ,";}
        if (checkDateD.isSelected()) {cm2.addColumn(c8); sql+="dateD ,";}
        if (checkDateF.isSelected()) {cm2.addColumn(c9); sql+="dateF ,";}
        if (checkPaysAcc.isSelected()) {cm2.addColumn(c10); sql+="paysAcc ,";}
        if (checkEtabAcc.isSelected()) {cm2.addColumn(c11); sql+="etabAcc ,";}
        if (checkDomaine.isSelected()) {cm2.addColumn(c12); sql+="domaine ,";}
        if (checkTypeS.isSelected()) {cm2.addColumn(c13); sql+="typeStage ,";}
        if (checkAllocation.isSelected()){ cm2.addColumn(c14); sql+="allocation ,";}
        if (checkBillet.isSelected()) {cm2.addColumn(c15); sql+="billet ,";}
        if (checkAnn.isSelected()) {cm2.addColumn(c16); sql+="annFinac ,";}
        if (checkFac.isSelected()) {cm2.addColumn(c17); sql+="faculté ,";}
        TabInfosMini.setColumnModel(cm2);
        sql=sql.substring(0, sql.length()-2);
        sql+=" from infos ";
    }//GEN-LAST:event_jMyBottom1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    TabInfosMini.setModel(frmInfos.TabInfos.getModel());
    TabInfosMini.getTableHeader().setReorderingAllowed(false);
        TabInfosMini.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,14));
TabInfosMini.getTableHeader().setOpaque(false);
TabInfosMini.getTableHeader().setBackground(new Color(32, 136, 203));
TabInfosMini.getTableHeader().setForeground(new Color(255, 255, 255));
    
    }//GEN-LAST:event_formWindowOpened

    private void checkDateFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDateFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDateFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyBottom BtnImprimerMini;
    private javax.swing.JTable TabInfosMini;
    private javax.swing.JCheckBox checkAllocation;
    private javax.swing.JCheckBox checkAnn;
    private javax.swing.JCheckBox checkBillet;
    private javax.swing.JCheckBox checkBénéficiaire;
    private javax.swing.JCheckBox checkDateD;
    private javax.swing.JCheckBox checkDateF;
    private javax.swing.JCheckBox checkDateN;
    private javax.swing.JCheckBox checkDomaine;
    private javax.swing.JCheckBox checkDurée;
    private javax.swing.JCheckBox checkEtabAcc;
    private javax.swing.JCheckBox checkFac;
    private javax.swing.JCheckBox checkGrade;
    private javax.swing.JCheckBox checkNomAr;
    private javax.swing.JCheckBox checkNomFr;
    private javax.swing.JCheckBox checkNuméro;
    private javax.swing.JCheckBox checkPaysAcc;
    private javax.swing.JCheckBox checkSexe;
    private javax.swing.JCheckBox checkTypeS;
    private javax.swing.JLabel jLabel1;
    private controls.JMyBottom jMyBottom1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
